name: CoGuard Scanning for infrastructure related files
run-name: Pull request ${{github.event.number}} is being scanned for misconfigurations.
on:
  - pull_request

permissions:
  actions: none
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  run_coguard_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: true

      - name: Delete the faulty test clusters from the coverity tranlation submodule
        run: rm -rf src/coverity_integration/tests
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.9'
      - run: pip3 install pytest coverage
      - run: pip3 install -r requirements.txt
      - run: pip3 install coguard-cli
      - env:
          COGUARD_USER_NAME: ${{secrets.CoGuardTestUserName}}
          COGUARD_PASSWORD: ${{secrets.CoGuardTestPassword}}
        run: (cd src && python3 -m coguard_cli --minimum-fail-level=6 --output-format=sarif --coguard-api-url https://test.coguard.io/server --coguard-auth-url https://test.coguard.io/auth folder ..)
      - run: ls -lah
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@a57c67b89589d2d13d5ac85a9fc4679c7539f94c
        with:
          sarif_file: src/result.sarif.json
          category: CoGuard
      - name: Fail job if there is a result
        run: test -z $(jq -r '.runs[0].results[]' src/result.sarif.json)
