on:
  workflow_dispatch:
    inputs:
      istest:
        type: boolean
        description: Print all checksums in case things change
        default: false

permissions:
  actions: none
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  run-integrations-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: true
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.9'
      - run: pip3 install pytest coverage
      - run: pip3 install -r requirements.txt
      - run: pip3 install coguard-cli
      - env:
          COGUARD_USER_NAME: ${{secrets.CoGuardTestUserName}}
          COGUARD_PASSWORD: ${{secrets.CoGuardTestPassword}}
        run: make integration-test IS_TEST=${{ inputs.istest }}
