on:
  pull_request:
    branches:
      - master
    push:

permissions:
  actions: none
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: read

jobs:
  run-linting:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          submodules: true
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.9'
      - run: pip3 install pylint ansible-lint
      - run: pip3 install -r requirements.txt
      - run: make lint
