name: Push coguard-cli image to repository

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: find_version_tag
      run: |
        CURRENT_COGUARD_VERSION=$(grep version setup.cfg | awk -F' = ' '{print $2}');
        echo "CURRENT_COGUARD_VERSION=$CURRENT_COGUARD_VERSION" >> $GITHUB_ENV;

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: coguard-cli-container:${{ env.CURRENT_COGUARD_VERSION }}
        build-args:
          - COGUARD_VERSION=${{ env.CURRENT_COGUARD_VERSION }}
        context: docker
